import type { AuditLog } from "@/types"

const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR

function ts(offsetMs: number): string {
  return new Date(Date.now() - offsetMs).toISOString()
}

function id(n: number): string {
  return `demo-${n.toString().padStart(6, "0")}`
}

const DEMO_LEAD_IDS = {
  fatima: "00000000-0000-0000-0000-00000000a001",
  ahmad: "00000000-0000-0000-0000-00000000a002",
  noura: "00000000-0000-0000-0000-00000000a003",
  yousef: "00000000-0000-0000-0000-00000000a004",
  sara: "00000000-0000-0000-0000-00000000a005",
  abdullah: "00000000-0000-0000-0000-00000000a006",
  mariam: "00000000-0000-0000-0000-00000000a007",
  hamad: "00000000-0000-0000-0000-00000000a008",
} as const

export function getMockAuditLogs(): AuditLog[] {
  const logs: AuditLog[] = [
    {
      id: id(1),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.fatima,
      action: "INSERT",
      new_values: {
        first_name_ar: "فاطمة",
        last_name_ar: "العنزي",
        phone: "+96599887766",
        source: "instagram",
        pipeline_stage: "new",
      },
      changed_fields: ["first_name_ar", "last_name_ar", "phone", "source", "pipeline_stage"],
      user_id: "demo-agent-1",
      user_email: "nora.khalid@ktech.edu.kw",
      created_at: ts(15 * 60 * 1000),
    },
    {
      id: id(2),
      table_name: "appointments",
      record_id: "demo-appt-001",
      action: "INSERT",
      new_values: {
        appointment_type: "campus_tour",
        scheduled_at: new Date(Date.now() + 2 * DAY).toISOString(),
        location: "ktech Adailiya Campus",
      },
      changed_fields: ["appointment_type", "scheduled_at", "location"],
      user_id: "demo-agent-2",
      user_email: "abdulwahab.boodai@ktech.edu.kw",
      created_at: ts(45 * 60 * 1000),
    },
    {
      id: id(3),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.ahmad,
      action: "UPDATE",
      old_values: { pipeline_stage: "contacted", contact_status: "warm" },
      new_values: { pipeline_stage: "interviewed", contact_status: "hot" },
      changed_fields: ["pipeline_stage", "contact_status"],
      user_id: "demo-agent-3",
      user_email: "ahmed.hassan@ktech.edu.kw",
      created_at: ts(2 * HOUR),
    },
    {
      id: id(4),
      table_name: "payments",
      record_id: "demo-pay-001",
      action: "INSERT",
      new_values: {
        amount: 1250,
        currency: "KWD",
        status: "succeeded",
        method: "myfatoorah",
      },
      changed_fields: ["amount", "currency", "status", "method"],
      user_id: "demo-system",
      user_email: "system@ktech.edu.kw",
      created_at: ts(3 * HOUR),
    },
    {
      id: id(5),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.noura,
      action: "UPDATE",
      old_values: { assigned_to: null },
      new_values: { assigned_to: "demo-agent-4" },
      changed_fields: ["assigned_to"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(4 * HOUR),
    },
    {
      id: id(6),
      table_name: "students",
      record_id: "demo-student-001",
      action: "INSERT",
      new_values: {
        first_name_ar: "يوسف",
        last_name_ar: "المطيري",
        program: "Cybersecurity Diploma",
        cohort: "Fall 2026",
      },
      changed_fields: ["first_name_ar", "last_name_ar", "program", "cohort"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(5 * HOUR),
    },
    {
      id: id(7),
      table_name: "appointments",
      record_id: "demo-appt-002",
      action: "UPDATE",
      old_values: { scheduled_at: new Date(Date.now() + 1 * DAY).toISOString(), status: "scheduled" },
      new_values: { scheduled_at: new Date(Date.now() + 3 * DAY).toISOString(), status: "rescheduled" },
      changed_fields: ["scheduled_at", "status"],
      user_id: "demo-agent-5",
      user_email: "lina.mahmoud@ktech.edu.kw",
      created_at: ts(6 * HOUR),
    },
    {
      id: id(8),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.yousef,
      action: "UPDATE",
      old_values: { priority: "normal" },
      new_values: { priority: "critical" },
      changed_fields: ["priority"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(8 * HOUR),
    },
    {
      id: id(9),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.sara,
      action: "INSERT",
      new_values: {
        first_name_ar: "سارة",
        last_name_ar: "الرشيدي",
        source: "whatsapp_ai",
        pipeline_stage: "new",
      },
      changed_fields: ["first_name_ar", "last_name_ar", "source", "pipeline_stage"],
      user_id: "demo-system",
      user_email: "system@ktech.edu.kw",
      created_at: ts(10 * HOUR),
    },
    {
      id: id(10),
      table_name: "profiles",
      record_id: "demo-profile-001",
      action: "UPDATE",
      old_values: { full_name: "Sarah J.", phone: null },
      new_values: { full_name: "Sarah Jones", phone: "+96599000111" },
      changed_fields: ["full_name", "phone"],
      user_id: "demo-agent-6",
      user_email: "sarah.jones@ktech.edu.kw",
      created_at: ts(1 * DAY + 1 * HOUR),
    },
    {
      id: id(11),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.abdullah,
      action: "DELETE",
      old_values: {
        first_name_ar: "عبدالله",
        last_name_ar: "الصباح",
        pipeline_stage: "lost",
      },
      changed_fields: [],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(1 * DAY + 3 * HOUR),
    },
    {
      id: id(12),
      table_name: "payments",
      record_id: "demo-pay-002",
      action: "UPDATE",
      old_values: { status: "pending" },
      new_values: { status: "succeeded" },
      changed_fields: ["status"],
      user_id: "demo-system",
      user_email: "system@ktech.edu.kw",
      created_at: ts(1 * DAY + 5 * HOUR),
    },
    {
      id: id(13),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.mariam,
      action: "UPDATE",
      old_values: { pipeline_stage: "applicant", actual_gpa: 78 },
      new_values: { pipeline_stage: "accepted", actual_gpa: 84 },
      changed_fields: ["pipeline_stage", "actual_gpa"],
      user_id: "demo-agent-7",
      user_email: "omar.farid@ktech.edu.kw",
      created_at: ts(1 * DAY + 7 * HOUR),
    },
    {
      id: id(14),
      table_name: "appointments",
      record_id: "demo-appt-003",
      action: "UPDATE",
      old_values: { status: "scheduled" },
      new_values: { status: "completed" },
      changed_fields: ["status"],
      user_id: "demo-agent-3",
      user_email: "ahmed.hassan@ktech.edu.kw",
      created_at: ts(1 * DAY + 9 * HOUR),
    },
    {
      id: id(15),
      table_name: "students",
      record_id: "demo-student-002",
      action: "UPDATE",
      old_values: { gpa: 76 },
      new_values: { gpa: 81 },
      changed_fields: ["gpa"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(2 * DAY + 2 * HOUR),
    },
    {
      id: id(16),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.hamad,
      action: "INSERT",
      new_values: {
        first_name_ar: "حمد",
        last_name_ar: "الفضلي",
        source: "exhibition_kuwait_fair",
        pipeline_stage: "new",
      },
      changed_fields: ["first_name_ar", "last_name_ar", "source", "pipeline_stage"],
      user_id: "demo-agent-8",
      user_email: "dana.ali@ktech.edu.kw",
      created_at: ts(2 * DAY + 4 * HOUR),
    },
    {
      id: id(17),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.fatima,
      action: "UPDATE",
      old_values: { contact_count: 0 },
      new_values: { contact_count: 1, last_contacted_at: ts(2 * DAY + 6 * HOUR) },
      changed_fields: ["contact_count", "last_contacted_at"],
      user_id: "demo-agent-1",
      user_email: "nora.khalid@ktech.edu.kw",
      created_at: ts(2 * DAY + 6 * HOUR),
    },
    {
      id: id(18),
      table_name: "appointments",
      record_id: "demo-appt-004",
      action: "INSERT",
      new_values: {
        appointment_type: "phone_call",
        scheduled_at: new Date(Date.now() + 1 * DAY).toISOString(),
      },
      changed_fields: ["appointment_type", "scheduled_at"],
      user_id: "demo-agent-5",
      user_email: "lina.mahmoud@ktech.edu.kw",
      created_at: ts(2 * DAY + 8 * HOUR),
    },
    {
      id: id(19),
      table_name: "payments",
      record_id: "demo-pay-003",
      action: "INSERT",
      new_values: {
        amount: 850,
        currency: "KWD",
        status: "pending",
        method: "bank_transfer",
      },
      changed_fields: ["amount", "currency", "status", "method"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(3 * DAY + 1 * HOUR),
    },
    {
      id: id(20),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.noura,
      action: "UPDATE",
      old_values: { lost_reason_id: null, pipeline_stage: "interviewed" },
      new_values: { lost_reason_id: "competitor-aub", pipeline_stage: "lost" },
      changed_fields: ["lost_reason_id", "pipeline_stage"],
      user_id: "demo-agent-4",
      user_email: "yousef.ward@ktech.edu.kw",
      created_at: ts(3 * DAY + 4 * HOUR),
    },
    {
      id: id(21),
      table_name: "profiles",
      record_id: "demo-profile-002",
      action: "INSERT",
      new_values: { full_name: "Aldana Ali", role: "agent", email: "aldana.ali@ktech.edu.kw" },
      changed_fields: ["full_name", "role", "email"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(3 * DAY + 7 * HOUR),
    },
    {
      id: id(22),
      table_name: "students",
      record_id: "demo-student-003",
      action: "UPDATE",
      old_values: { placement_level: "L2" },
      new_values: { placement_level: "L3" },
      changed_fields: ["placement_level"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(4 * DAY + 2 * HOUR),
    },
    {
      id: id(23),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.ahmad,
      action: "UPDATE",
      old_values: { source: "facebook" },
      new_values: { source: "referral" },
      changed_fields: ["source"],
      user_id: "demo-admin-1",
      user_email: "adel@ktech.edu.kw",
      created_at: ts(4 * DAY + 6 * HOUR),
    },
    {
      id: id(24),
      table_name: "appointments",
      record_id: "demo-appt-005",
      action: "UPDATE",
      old_values: { status: "scheduled" },
      new_values: { status: "no_show" },
      changed_fields: ["status"],
      user_id: "demo-agent-7",
      user_email: "omar.farid@ktech.edu.kw",
      created_at: ts(5 * DAY + 3 * HOUR),
    },
    {
      id: id(25),
      table_name: "leads",
      record_id: DEMO_LEAD_IDS.sara,
      action: "UPDATE",
      old_values: { pipeline_stage: "new" },
      new_values: { pipeline_stage: "contacted" },
      changed_fields: ["pipeline_stage"],
      user_id: "demo-system",
      user_email: "automation@ktech.edu.kw",
      created_at: ts(5 * DAY + 6 * HOUR),
    },
  ]

  return logs
}

export function filterMockAuditLogs(
  logs: AuditLog[],
  opts: { search?: string; filterTable?: string; filterAction?: string }
): AuditLog[] {
  const search = opts.search?.trim().toLowerCase()
  return logs.filter((log) => {
    if (opts.filterTable && opts.filterTable !== "all" && log.table_name !== opts.filterTable) return false
    if (opts.filterAction && opts.filterAction !== "all" && log.action !== opts.filterAction) return false
    if (search) {
      const haystack = [
        log.user_email,
        log.table_name,
        log.record_id,
        ...(log.changed_fields || []),
      ]
        .filter(Boolean)
        .join(" ")
        .toLowerCase()
      if (!haystack.includes(search)) return false
    }
    return true
  })
}
