-- Seed American curriculum schools in Kuwait
INSERT INTO schools (name_en, name_ar, school_type, is_active) VALUES
-- Well-known American curriculum schools in Kuwait
('American International School of Kuwait (AIS)', 'المدرسة الأمريكية الدولية في الكويت', 'us', true),
('American Creativity Academy (ACA)', 'أكاديمية الإبداع الأمريكية', 'us', true),
('American United School of Kuwait (AUS)', 'المدرسة الأمريكية المتحدة في الكويت', 'us', true),
('Universal American School (UAS)', 'المدرسة الأمريكية العالمية', 'us', true),
('Kuwait American School (KAS)', 'مدرسة الكويت الأمريكية', 'us', true),
('American Baccalaureate School (ABS)', 'مدرسة البكالوريا الأمريكية', 'us', true),
('Gulf American School', 'مدرسة الخليج الأمريكية', 'us', true),
('Al-Bayan Bilingual School (BBS)', 'مدرسة البيان ثنائية اللغة', 'us', true),
('The American School of Kuwait (TASK)', 'المدرسة الأمريكية بالكويت', 'us', true),
('American Academy for Girls (AAG)', 'الأكاديمية الأمريكية للبنات', 'us', true),
('Kuwait National English School (KNES)', 'مدرسة الكويت الوطنية الإنجليزية', 'us', true),
('Al-Ruya Bilingual School (RBS)', 'مدرسة الرؤية ثنائية اللغة', 'us', true),
('Fawzia Sultan International School (FSIS)', 'مدرسة فوزية السلطان الدولية', 'us', true),
('American International Academy (AIA)', 'الأكاديمية الأمريكية الدولية', 'us', true),
('Gulf English School (GES)', 'مدرسة الخليج الإنجليزية', 'us', true),
('New England School of Kuwait', 'مدرسة نيو إنجلاند في الكويت', 'us', true),
('Dasman Bilingual School (DBS)', 'مدرسة دسمان ثنائية اللغة', 'us', true),
('Al-Ahliah School of Kuwait', 'المدرسة الأهلية في الكويت', 'us', true),
('Kuwait Bilingual School (KBS)', 'مدرسة الكويت ثنائية اللغة', 'us', true),
('Al-Salam Bilingual School', 'مدرسة السلام ثنائية اللغة', 'us', true),
('Jabriya International School', 'مدرسة الجابرية الدولية', 'us', true),
('Kuwait International English School (KIES)', 'مدرسة الكويت الدولية الإنجليزية', 'us', true),
('Al-Nibras International School', 'مدرسة النبراس الدولية', 'us', true),
('Oxford Academy Kuwait', 'أكاديمية أكسفورد الكويت', 'us', true),
('Aquila American School', 'مدرسة أكويلا الأمريكية', 'us', true),
('Grace American School', 'مدرسة جريس الأمريكية', 'us', true),
('Future Bilingual School', 'مدرسة المستقبل ثنائية اللغة', 'us', true);
